// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPC.proto

package com.grpctest;

public final class GRPC {
  private GRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_text_HelloWorldRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_text_HelloWorldRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_text_HelloWorldResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_text_HelloWorldResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGRPC.proto\022\tgrpc_text\" \n\021HelloWorldReq" +
      "uest\022\013\n\003msg\030\001 \001(\t\"!\n\022HelloWorldResponse\022" +
      "\013\n\003msg\030\001 \001(\t2`\n\014HelloService\022P\n\017HelloWor" +
      "ldPrint\022\034.grpc_text.HelloWorldRequest\032\035." +
      "grpc_text.HelloWorldResponse\"\000B\020\n\014com.gr" +
      "pctestP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_text_HelloWorldRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_text_HelloWorldRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_text_HelloWorldRequest_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_grpc_text_HelloWorldResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_text_HelloWorldResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_text_HelloWorldResponse_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
