// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPC.proto

package com.grpctest;

public interface HelloWorldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpctest.HelloWorldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
